### ISSUE TITLE
Install command not work for macOS Mojave

### ISSUE THREAD

**Issue by cyb3rsalih** [tomnomnom/httprobe#10]
I re-install go both from official and with brew installer. But there is no difference. 

After command : `go get -u github.com/tomnomnom/httprobe` execute nothing is change. There is no output in terminal also.

**Comment by Afolic** [comment]
I am also having the same issue, no output on my linux distro

**Comment by samani15** [comment]
i m facing same problem. cant install httprobe.... plz reply if u find any fix!

**Comment by cyb3rsalih** [comment]
Solved! 
My path was
`export PATH="/usr/local/go/bin:$PATH"`

When I run
`find / -type f -name httprobe`
Found it at `/Users/user/go/bin/httprobe`

And when you add `/Users/user/go/bin` to path with,
`export PATH='/Users/user/go/bin/':$PATH`

Now httprobe works.

**Comment by Afolic** [comment]
Figured it out also, it also had something to do with my path, thanks

**Comment by samani15** [comment]
can any 1 can fix on teamviewer ??

**Comment by cyb3rsalih** [comment]
@samani15  send me email mehmetsalihbindak@gmail.com

**Comment by n00b1t4** [comment]
@cyb3rsalih can you remote my laptop too ? to install httprobe

**Comment by Muhammad-Qasim-Munir** [comment]
If someone is still having the issue just ping me!
