### ISSUE TITLE
httprobe: not found command.

### ISSUE THREAD

**Issue by Nepsec** [tomnomnom/httprobe#20]
Hi I'm trying to install httprobe with go get in windows sub system (ubuntu), it's not working. Can I use httprobe in windows subsystem?

**Comment by gopinath6** [comment]
@Nepsec  Any info on how to use on windows?

**Comment by m4d0u1** [comment]
This will help you:
https://github.com/nahamsec/lazyrecon/issues/21#issuecomment-519013847
