### ISSUE TITLE
Max concurrency?

### ISSUE THREAD

**Issue by marcelo321** [tomnomnom/httprobe#33]
Hello tomnomnom!

I have a short question, does httprobe have a max value for concurrency?

i am running it against +200k subdomains and sometimes even more, and it is a little bit slow with `-c 50` provided. Is there a max value for the -c flag? any other method to speed this up without breaking everything?

Have a good day.

**Comment by geeknik** [comment]
I regularly use `-c 200` with no problem against large data sets but every network is different so YMMV. Good luck!

**Comment by marcelo321** [comment]
I don't know why I didn't close this already. Thanks!
