### ISSUE TITLE
Not download httprobe

### ISSUE THREAD

**Issue by densdiego** [tomnomnom/httprobe#44]
Hi,

i have a problem with the Httprobe because not download..

sorry for my english XD

order for install..

Apt install golang (working done)
now
go get -u github.com/tomnomnom/httprobe  (not error message, but dont download anything..)

attached screenshots.

https://ibb.co/c19P9Gb

https://ibb.co/QQYXKfF

upload photos from ImgBB.

**Comment by densdiego** [comment]
How resolv this problem?

**Comment by rakshitks** [comment]
Follow this steps to install it worked for me!!

git  clone https://github.com/tomnomnom/httprobe.git
cd httprobe/
go build
sudo mv httprobe /usr/local/bin/

Open new terminal and try 
httprobe --help

**Comment by densdiego** [comment]
> git clone https://github.com/tomnomnom/httprobe.git

THAAAAAAAAAAAAANKS
